<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260211122653 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE reading (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value INT NOT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, meter_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C11AFC416E15CA9E ON reading (meter_id)');
        $this->addSql('ALTER TABLE reading ADD CONSTRAINT FK_C11AFC416E15CA9E FOREIGN KEY (meter_id) REFERENCES meter (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE reading DROP CONSTRAINT FK_C11AFC416E15CA9E');
        $this->addSql('DROP TABLE reading');
    }
}
